feat(app): Реализован сайт новостей
VeronikaBulaeva/hacker-news pull request #1
Opened 2024-07-24 16:07 UTC by VeronikaBulaeva

Реализован вывод списка новостей и новости отдельно, с использованием Hacker News API

2024-07-24 18:20 UTC, Kimiyori requested changes

2024-07-24 18:20 UTC, Kimiyori commented on src/components/Comments/Comments.tsx
> +              <SecondText>{time_ago}</SecondText>
что за странные названия) они же ни о чем не говорят

2024-07-24 18:20 UTC, Kimiyori commented on src/components/Comments/Comments.tsx
> +          ) : null}
так короче 
`          {!!comments.length && (
            <CommentButton onClick={changeVisibility}>
              {isShown ? "Скрыть ответы" : "Показать ответы"}
            </CommentButton>
          )}`

2024-07-24 18:20 UTC, Kimiyori commented on src/components/Comments/Comments.tsx
> +        <Loader />
а если нет комментов по каким-то причинам, то будет все равно лоадер? Я бы переписал под какой-нибудь suspense, будет куда красивее и меньше ошибок  вбудущем

2024-07-24 18:20 UTC, Kimiyori commented on src/components/Comments/Comments.tsx
> +const Comments: FC<FeedDataType> = ({
норм, но типы лучше в одном файле с компонентом хранить, в крайнем случае в соседнем файле

2024-07-24 18:20 UTC, Kimiyori commented on src/components/Header/Header.tsx
> +        <HeaderLink to={`/newsList/1`}>
при передаче строки не обязательно в {} окружать его

2024-07-24 18:20 UTC, Kimiyori commented on src/components/Header/Header.tsx
> +          <FirstText>Hacker News</FirstText>
опять нейминг странный и он не так уж и нужен, т.к. если под каждый вид текста делать отдельный компонент... с у ма сойти можно

2024-07-24 18:20 UTC, Kimiyori commented on src/components/NewsList/List/List.tsx
> +                      : undefined
опять же, это можно сократить до &&

2024-07-24 18:20 UTC, Kimiyori commented on src/components/style.ts
> +  @media screen and (max-width: 576px) {
я бы в константы вынес значения вроде 576

2024-07-24 18:20 UTC, Kimiyori commented on src/pages/NewsListPage/NewsList.tsx
> +  }, [fetchData, id]);
повторяется код, можно вынести его

2024-07-24 18:20 UTC, Kimiyori commented on src/components/NewsList/List/List.tsx
> +                comments_count={news.comments_count}
{...news}

2024-07-24 18:22 UTC, Kimiyori commented
Также стоит добавить скелетоны когда данные обновляются после повторной подгрузки. Например при нажатии на кнопку обновления списка, юзер не видит ничего и по итогу может жмякнуть хоть 10 раз. Короче нужен дизейбл кнопки на время обновления + визуальное обновление данных

2024-07-24 18:24 UTC, Kimiyori commented on src/components/Comments/Comments.tsx
> +            comments.map((comment) => (
не пойдет тут сразу фильтровать по delete ||dead?

2024-07-24 18:26 UTC, Kimiyori commented on src/components/style.ts
> +export const NewsItemLink = styled(Link)`
вообще сувать все стили в один файл плохо. Представь большой проект с сотнями стилей и все в одном файле) Если стилей немного, то можно прям в том же файле где используется их писать или где-нибудь рядом с припиской name.styles.tsx

2024-07-24 18:30 UTC, Kimiyori commented on src/components/style.ts
> +`;
а в чем проблема использовать h теги?) Можно добавить общие стили, а потом просто пропами передавать в стили то что у них отличается) В этом же и суть cssinjs

2024-07-24 18:51 UTC, VeronikaBulaeva commented on src/components/Comments/Comments.tsx
> +        <Loader />
нет, лоадера не будет, т.к. комменты по дефолту пустой массив, а пустой массив это true

2024-07-24 18:53 UTC, VeronikaBulaeva commented on src/components/Header/Header.tsx
> +          <FirstText>Hacker News</FirstText>
так это стилизация, а не компоненты
У меня используется 3 вида текста на всём сайте это first, second и текст для юзера, который называется UserText

2024-07-24 19:06 UTC, VeronikaBulaeva commented on src/components/Comments/Comments.tsx
> +              <SecondText>{time_ago}</SecondText>
Не совсем понимаю о чем должно говорить название стилизации текста)

2024-07-24 19:08 UTC, VeronikaBulaeva commented on src/components/Comments/Comments.tsx
> +const Comments: FC<FeedDataType> = ({
Это универсальный тип для нескольких сущностей, поэтому и вынесен

2024-07-24 19:12 UTC, VeronikaBulaeva commented on src/components/NewsList/List/List.tsx
> +                      : undefined
нет, именно здесь нельзя, т.к. даже IDE выдает ошибку о несоответствие типов
![Безымянный](https://github.com/user-attachments/assets/f19a3c3d-0c24-48a7-98fb-652748b0da75)

2024-07-24 19:15 UTC, VeronikaBulaeva commented on src/pages/NewsListPage/NewsList.tsx
> +  }, [fetchData, id]);
Не совсем поняла про каке ты повторение)
Есть похожий useEffect, но там и зависимости другие, короче, только то что там есть интервал похоже
Или я не про то подумала)

2024-07-25 19:23 UTC, Kimiyori commented on src/components/Comments/Comments.tsx
> +              <SecondText>{time_ago}</SecondText>
Достаточно просто Text, Typography или что-то такое. Названия должны о чем-то говорить, но что означает second first text не ясно, Лучше делать дженерик названия для общих компонентов, меняя стили по пропам

2024-07-25 19:26 UTC, Kimiyori commented on src/components/Comments/Comments.tsx
> +const Comments: FC<FeedDataType> = ({
лучше так не делать, потом если надо будет что-то изменить, а этот общий компонент уже много где будет - получишь лишний гемор. Лучше создать под каждый компонент свой интерфейс, а если он повторяет какие-то общие поля, то просто расширить его от того поля.

2024-07-25 19:33 UTC, Kimiyori commented on src/components/NewsList/List/List.tsx
> +                      : undefined
а, я понял, ты же инлайн стили делаешь) я уже по привычке думаю это пропы к cssinjs... убери эти инлайн стили отовсюду

2024-07-25 19:35 UTC, Kimiyori commented on src/pages/NewsListPage/NewsList.tsx
> +  }, [fetchData, id]);
да, это довольно общий паттерн рефеча,  я бы его в отдельный хук вынес

2024-07-29 00:48 UTC, IvanKoigerov commented on src/components/style.ts
> +export const NewsItemLink = styled(Link)`
Согласен, только ts)

2024-07-29 01:39 UTC, IvanKoigerov reviewed
Хочу чтобы ты потрогала преттер и eslint, потрогай и добавь наши конфиги
Также в дальнейшем добавляй их в свои задания

2024-07-29 01:39 UTC, IvanKoigerov commented on src/components/Header/Header.tsx
> +      <HeaderSec>
Не сокращаем никогда такие вещи

2024-07-29 01:39 UTC, IvanKoigerov commented on src/components/NewsList/List/List.tsx
> +      )}
Странно, что показываешь лоудинг, когда у тебя нет новостей лоудер, а если их вообще не будет?  не совсем корректное проведение
Также бы хотелось при кажатии на кнопку обновлении, ты видел, что обновляешь и видишь лоудер 

Также не нужно тут оборачивать в <>

ещё одна проблема, в том, что ты анмаунтишь все новости, когда загружаешь данные, а это потеря производительности

2024-07-29 01:39 UTC, IvanKoigerov commented on src/pages/NewsPage/NewsPage.tsx
> +      });
обычно если используют запросы таким образом, то их закидывают в стор, нет смысла тут хранить 
А также у тебя ниже некорректно описан эффект, у тебя нет подписки на используеммые там фетч дата

2024-07-29 01:39 UTC, IvanKoigerov commented on src/pages/NewsPage/NewsPage.tsx
> +    const id = setInterval(fetchComments, 60000);
Лучше всего это именовать не просто id, а какой это id, чего он

2024-07-29 01:39 UTC, IvanKoigerov commented on src/pages/NewsPage/NewsPage.tsx
> +    const id = setInterval(fetchComments, 60000);
А ещё у тебя повторяются сущности, два id на странице

2024-07-29 01:39 UTC, IvanKoigerov commented on src/pages/NewsPage/NewsPage.tsx
> +      });
нейм не очень getNews это как взять все новости, как и получить одну новость, так что не совсем понятно, что именно ты тут получаешь, а это плохо

Также имя файла, тоже непонятно это одна или много новостей, нужно четче именовать такие вещи

2024-07-29 01:39 UTC, IvanKoigerov commented on src/pages/NewsPage/NewsPage.tsx
> +};
очент странно так писать по настоящему)
Обычно выносят, когда так пишут из общего if, тк это читабельнее

Но я писал выше про другие новости, как бы я хотел видеть

2024-07-29 01:39 UTC, IvanKoigerov commented on src/requests/requests.ts
> +};
в задании написано, что нужно получить именно 100, ну ладно

2024-07-29 01:39 UTC, IvanKoigerov commented on src/pages/NewsPage/NewsPage.tsx
> +                {dayjs(currentNews.time * 1000).format("DD.MM.YYYY в HH:mm")}
не совсем круто на месте вычислять это значение, тк это каждый раз, при каждом рендере будет вычисляться
В данной ситуации это очень дешево, но на будущее помни, что это не всегда хорошо

2024-07-29 01:39 UTC, IvanKoigerov commented on src/pages/NewsPage/NewsPage.tsx
> +          <SecondSec>
Sec как я писал выше, не сокращаем названия никогда) 
Так наш код читабельнее

2024-07-29 01:39 UTC, IvanKoigerov commented on src/requests/requests.ts
нет никаких обработок ошибок у тебя, что грустно. Никто не знает отработает ли твой запрос или нет

2024-07-29 01:39 UTC, IvanKoigerov commented on src/pages/NewsListPage/NewsList.tsx
> +    const id = setInterval(fetchData, 60000);
тут те же проблемы, что и в другом месте

2024-07-29 01:39 UTC, IvanKoigerov commented on src/store/newsSlice.ts
> +  currentNews: FeedDataType | null;
имена типов не говорят к какой они сущности принадлежат, ItemDataType это может быть новость, может быть туду, может быть юзер и тд

2024-07-29 01:39 UTC, IvanKoigerov commented on src/pages/NewsListPage/NewsList.tsx
> +  }, [id]);
интересно, что тут у тебя callback, а в другом месте нет интересно)
А также именовать нужно лучше и такие функции fetchData чего, непонятно)

2024-07-29 01:39 UTC, IvanKoigerov commented on src/pages/NewsListPage/NewsList.tsx
> +      </UpdateButton>
Молодец, у тебя не будет лишний раз обновляться кнопка обновления

2024-07-29 01:39 UTC, IvanKoigerov commented on src/main.tsx
> +    </Provider>
Ту не должно быть ничего кроме App, этот компонент не для этого, он должен принимать в себя только мод и App

2024-07-29 01:39 UTC, IvanKoigerov commented on src/components/style.ts
> +  ${button}
Зачем так переиспользовать значения, если ты можешь создать дефолтную кнопку и уже ее использовать в styled

2024-07-29 01:39 UTC, IvanKoigerov commented on src/components/style.ts
> +  color: #1c1c27;
Хотелось бы видеть в теме это значение

2024-07-29 01:39 UTC, IvanKoigerov commented on src/components/style.ts
> +  color: #1c1c27;
Да и все цвета в принципе

2024-07-29 01:39 UTC, IvanKoigerov commented on src/components/style.ts
> +  padding: 30px 30px;
почему не просто padding

2024-07-29 01:39 UTC, IvanKoigerov commented on src/components/style.ts
> +  }
также хотелось бы видеть медиа значения в теме

2024-07-29 01:39 UTC, IvanKoigerov commented on src/components/style.ts
> +  margin: 10px 28px;
странные марджины, хотелось бы видеть марджины степени двойки 
ну а 10 норм можешь оствить

2024-07-29 01:39 UTC, IvanKoigerov commented on src/components/style.ts
> +    gap: 10px 25px;
нечетные значения не используем

2024-07-29 01:39 UTC, IvanKoigerov commented on src/components/style.ts
> +  gap: 35px;
тут тоже

2024-07-29 01:39 UTC, IvanKoigerov commented on src/components/style.ts
> +  padding: 15px 20px;
и тут

2024-07-29 01:39 UTC, IvanKoigerov commented on src/components/style.ts
> +`;
советую использовать глобальный css (css reset или нормалайз) или как-то их переписать глобвльно

2024-07-29 01:39 UTC, IvanKoigerov commented on src/components/style.ts
все нечетные паддинги и марджины нужно переделать на четные значения

2024-07-29 01:39 UTC, IvanKoigerov commented on src/components/style.ts
> +`;
Согласен, важно описывать h на странице

2024-07-29 01:39 UTC, IvanKoigerov commented on src/components/style.ts
> +  cursor: pointer;
почему у нас обычный div это pointer, такого не должно быть либо кнопка либо линк

2024-07-29 01:39 UTC, IvanKoigerov commented on src/components/style.ts
> +export const ItemBox = styled("div")`
что за item, когда пишешь в глобальном файле стиле, очень важно описывать названия привязываясь к сущности в которой ты это используешь, да и в принципе важно привязоваться к сущности, для понимания зачем этот компонент то нужен

2024-07-29 01:39 UTC, IvanKoigerov commented on src/components/style.ts
> +export const SecondSec = styled("div")`
у тебя итем называется секция, но при этом используешь див

2024-07-29 01:39 UTC, IvanKoigerov commented on src/components/style.ts
Подумай о симантике и сделай симантически верно свои компоненты, сейчас с этим проблемы

2024-07-31 16:14 UTC, Kimiyori commented on src/commons/Button.tsx
> +};
зачем button? у mui есть свой линк компонент, вот тут можно почитать https://mui.com/material-ui/integrations/routing/

2024-07-31 16:58 UTC, Kimiyori requested changes

2024-07-31 16:58 UTC, Kimiyori commented on src/commons/Button.tsx
> +};
зачем button? у mui есть свой линк компонент, вот тут можно почитать https://mui.com/material-ui/integrations/routing/

2024-07-31 16:58 UTC, Kimiyori commented on src/components/Comments/Comments.tsx
> +    <Suspense fallback={<Loader />}>
думаешь это тут будет работать?)

2024-07-31 16:58 UTC, Kimiyori commented on src/components/Comments/Comments.tsx
> +          <CommentButton component={'button'} onClick={changeVisibility}>
строки не обязательно в {} оборачивать

2024-07-31 16:58 UTC, Kimiyori commented on src/components/NewsList/List/List.tsx
> +    <Suspense fallback={<Loader />}>
А тут зачем саспенс?)

2024-07-31 16:58 UTC, Kimiyori commented on src/components/router-provider/index.tsx
> +          </Suspense>
а вот тут почему он один лишь обернут?

2024-07-31 16:58 UTC, Kimiyori commented on src/pages/NewsListPage/NewsList.tsx
> +  });
а что мешает это в хук вынести?

2024-07-31 16:58 UTC, Kimiyori commented on src/pages/NewsListPage/NewsList.tsx
> +  }
попробуй посмотреть в сторону error boundaries, в связке с suspense будет идти хорошо

2024-07-31 16:58 UTC, Kimiyori commented on src/pages/OneNewsPage/useGetNewById.ts
> +    [dispatch, getData],
почему это в getnews?

2024-07-31 16:58 UTC, Kimiyori commented on src/theme.ts
> +      xl: 1920,
они же там по дефолту стоят

2024-07-31 16:58 UTC, Kimiyori commented on src/commons/useRefetch.ts
> +const useRefetch = (callback: (args?: unknown) => unknown, timeout: number = 60000) => {
зачем unknown? ты же его используешь как ()=>void

2024-07-31 16:58 UTC, Kimiyori commented on src/components/Comments/Comments.tsx
> +          <img src={User} alt={'user'} width={40} height={40} />
попробуй использовать свои svg как компоненты

2024-07-31 16:58 UTC, Kimiyori commented on src/pages/NewsListPage/NewsList.tsx
> +      </Suspense>
почему только лист обрунула? у тебя во время показа лоадера слетает пагинация наверх

2024-07-31 16:58 UTC, Kimiyori commented on src/pages/OneNewsPage/OneNewsPage.tsx
> +const OneNewsPage: FC = () => {
что за название?) Лучше уж тогда NewsDetail

2024-07-31 16:58 UTC, Kimiyori commented on src/components/OneNews.tsx
> +        <UpdateButton component="button" onClick={() => window.location.reload()}>
вот так делать не надо, у нас же spa. Ты должна делать рефетч данных, а не перезагружать страницу

2024-07-31 16:58 UTC, Kimiyori commented on src/components/style.ts
>  `;
перебор делать для 2 стилей, при чем крайне дефолтных, отдельный стилизованный компонент

2024-07-31 16:58 UTC, Kimiyori commented on src/pages/NewsListPage/NewsList.tsx
> +  const List = lazy(() => import('@/components/NewsList/List/List'));
зачем внутрь запихнула?

2024-07-31 16:58 UTC, Kimiyori commented on src/pages/NewsListPage/NewsList.tsx
> +      <UpdateButton component="button" onClick={() => window.location.reload()}>
то же самое, так не надо

2024-07-31 16:58 UTC, Kimiyori commented on src/pages/OneNewsPage/useGetNewById.ts
> +          dispatch(updateComments(data.comments));
зачем вообще отдельно хранить комменты? ты же все равно обновляешь объект, просто оттуда его бери

2024-07-31 17:07 UTC, VeronikaBulaeva commented on src/pages/OneNewsPage/useGetNewById.ts
> +          dispatch(updateComments(data.comments));
я не храню комменты отдельно
этот экшен обновляет комменты текущей новости

2024-07-31 17:13 UTC, VeronikaBulaeva commented on src/pages/NewsListPage/NewsList.tsx
> +      </Suspense>
что бы кнопки не перерисовывались
могу всё обернуть)

2024-07-31 17:16 UTC, VeronikaBulaeva commented on src/theme.ts
> +      xl: 1920,
так если они прописаны, легче ориентироваться)

2024-07-31 17:17 UTC, VeronikaBulaeva commented on src/pages/OneNewsPage/useGetNewById.ts
> +    [dispatch, getData],
в смысле, почему в этом хуке?
потому что я не храню комменты отдельно, а получаю их из новости и обновляю

2024-07-31 17:19 UTC, VeronikaBulaeva commented on src/pages/NewsListPage/NewsList.tsx
> +  });
fetchData уже из хука
useRefetch тоже хук

2024-07-31 17:21 UTC, VeronikaBulaeva commented on src/components/router-provider/index.tsx
> +          </Suspense>
ErrorPage не требует этого, а NewsList внутри себя Suspense имеет

2024-07-31 17:22 UTC, VeronikaBulaeva commented on src/components/NewsList/List/List.tsx
> +    <Suspense fallback={<Loader />}>
для List...
как раз чтобы не перерисовывать кнопку апдейта постоянно

2024-07-31 17:25 UTC, VeronikaBulaeva commented on src/commons/Button.tsx
> +};
Потому что это дефолтная кнопка, сейчас она подходит как для link, так и для обычной кнопки, т.к. они абсолютно одинаковые
Для чего мне делать 2 одинаковые кнопки, если я могу сделать одну, таже основанную на MUIButton, у которой есть проп component, который может быть button или Link

2024-08-02 08:59 UTC, VeronikaBulaeva commented on src/pages/OneNewsPage/useGetNewById.ts
> +    [dispatch, getData],
сейчас этого уже нет, переделала логику)

2024-08-03 14:20 UTC, Kimiyori requested changes

2024-08-03 14:20 UTC, Kimiyori commented on src/components/router-provider/index.tsx
> +            <Suspense fallback={<Loader />}>
ты же можешь один раз обернуть роутер в это, не обязательно каждый компонент)

2024-08-03 14:20 UTC, Kimiyori commented on src/components/router-provider/index.tsx
>            </Suspense>
зачем порядок менять тут?

2024-08-03 14:20 UTC, Kimiyori commented on src/components/router-provider/index.tsx
> +            <Suspense fallback={<Loader />}>
да и вообще, посмотрел и оказывается саспенс плохо работает с редаксом, тут он вообще не отрабатывает.... так что лучше убрать наверное. Жесть конечно, такая громадина, а выхлопа нет...

2024-08-03 14:20 UTC, Kimiyori commented on src/pages/NewsDetail/NewsDetail.tsx
> +    <OneNews
NewsDetail, а этот компонет тогда NewsDetailPage

2024-08-03 14:20 UTC, Kimiyori commented on src/components/router-provider/index.tsx
> +const NewsList = lazy(() => import('@/pages/NewsListPage/NewsList'));
да  и раз от саспенса избавляется, то и lazy тут можно убрать

2024-08-05 16:19 UTC, Kimiyori approved these changes

2024-08-05 16:40 UTC, Kimiyori commented
только заметил, нету страницы с ошибкой при несуществующей новости

2024-08-05 16:41 UTC, Kimiyori commented
и кнопка комментов зачем-то отрабатывает, но зачем? она же не делает ничего

2024-08-05 16:45 UTC, Kimiyori commented
и отрбаотку ошибок еще бы улучшить. Например при таком урле будет вечный лоадер http://localhost:3000/newsList/ererg, а кнопка hackernews становится неактивна

2024-08-12 10:52 UTC, IvanKoigerov commented on src/components/Comments/CommenList.tsx
> +const CommentList: FC<CommentListType> = ({ currentNews }) => {
Не используем FC, уже несколько раз об этом комменты писал

2024-08-12 10:52 UTC, IvanKoigerov commented on src/components/Comments/CommenList.tsx
> +        ))}
ты в такой ситуации делаешь один лишний пробег по всему массиву, не совсем это выгодно

2024-08-12 10:52 UTC, IvanKoigerov commented on src/components/Comments/Comments.tsx
> +          .map((comment) => <Comments {...comment} key={comment.id} />)}
ты в такой ситуации делаешь один лишний пробег по всему массиву, не совсем это выгодно.
Ещё в map компоненты переносим на новую строку

2024-08-12 10:52 UTC, IvanKoigerov commented on src/components/Comments/Comments.tsx
> +`;
Не люблю margin, когда у нас уже есть gap, то я бы его использовал

2024-08-12 10:52 UTC, IvanKoigerov commented on src/components/Header/Header.tsx
> +    margin-inline: auto;
Точно нужно?

2024-08-12 10:52 UTC, IvanKoigerov commented on src/components/NewsDetail.tsx
> +    max-width: 70%;
не круто использовать % какие-то кроме 50% и 100%, все остальное не очень удобная вещь и красива, ты не можешь так отследить его корректный размер и тд

2024-08-12 10:52 UTC, IvanKoigerov commented on src/components/NewsDetail.tsx
> +    border: transparent solid 1px;
а зачем тебе бесцветный бордер

2024-08-12 10:52 UTC, IvanKoigerov commented on src/components/NewsDetail.tsx
> +    padding: 16px 0;
почему с паддингом не используешь как с марджином inline и block

2024-08-12 10:52 UTC, IvanKoigerov commented on src/components/NewsList/List/List.tsx
> +};
я уже писал почему плохо так использовать лоадинг

2024-08-12 10:52 UTC, IvanKoigerov commented on src/components/NewsList/List/List.tsx
> +};
а ещё такие вещи лучше выносить в отдельный if, а то читабельность теряется

2024-08-12 10:52 UTC, IvanKoigerov commented on src/components/NewsList/List/List.tsx
> +    margin-top: 16px;
смотри почему не очень круто использовать margin
У тебя в такой ситуации элемент думает о том, где он должен отображаться и как, нуда он должен двигаться, а это не очень круто, что элемент менеджит свое расположение в родителе. Желательно он не должен понимать о том, каким образом его отображают и как его двигают, поэтому и используем gap
`+` не надо у каждого элемента этот марджин указывать, лучше всего это контролировать через родителя

Да и в принципе margin это злоооооооооооо по настоящему, его надо страться как можно меньших случаях использовать, только лишь в самых крайних случаях

2024-08-12 10:52 UTC, IvanKoigerov commented on src/components/Comments/CommenList.tsx
> +const CommentList: FC<CommentListType> = ({ currentNews }) => {
везде исправь

2024-08-12 10:52 UTC, IvanKoigerov commented on src/components/NewsDetail.tsx
> +      {isLoading ? <Loader /> : <CommentList currentNews={currentNews} />}
ты тут в любом случае удаляешь весь свой список, которые уже есть в доме, а это не круто, не должно быть тут в CommentList какая-то условная отрисовка

2024-08-12 10:52 UTC, IvanKoigerov commented on src/components/router-provider/index.tsx
> +  }, [location.pathname]);
А зачем тебе это?

2024-08-12 10:52 UTC, IvanKoigerov commented on src/pages/ErrorPage/ErrorPage.tsx
> +      <ButtonLink component={Link} to={MAIN_PAGE_ROUTE} color="primary" onClick={resetBoundary}
в sx больше 3х значений

2024-08-12 10:52 UTC, IvanKoigerov commented on src/pages/ErrorPage/ErrorPage.tsx
> +                  sx={{ maxWidth: 'max-content', mt: 5, p: 2, justifySelf: 'center' }}>
а ещё так не переносят. делают так 
```
<ButtonLink 
  component={Link} 
  to={MAIN_PAGE_ROUTE} 
  color="primary"
````

2024-08-15 22:18 UTC, IvanKoigerov commented on src/commons/Button.tsx
> +    box-shadow: ${({ theme }) => theme.palette.shadow.shadow};
имя конечно не очень) shadow
какой это shadow
и обычно перед этим пишется shadows, так как ты хранишь там много теней

2024-08-15 22:18 UTC, IvanKoigerov commented on src/components/NewsDetail.tsx
> +  }
а а обсуждали, что так делать плохо

2024-08-15 22:18 UTC, IvanKoigerov commented on src/components/NewsList/List/List.tsx
> +      {isLoading && <Loader />}
вот тут хорошо

2024-08-20 13:24 UTC, merged